apiVersion: v1 
kind: ConfigMap 
metadata:
  name: dreamflow-cms-configmap
  namespace: dreamflow
data:
  PGPASSWORD: qzs4slpx82ydx92y
  PGUSERNAME: doadmin
  PGPORT: "25060"
  PGDATABASE: dreamflow-cms-db
  PGHOST: kaynet-db-1-do-user-7235483-0.a.db.ondigitalocean.com
  SENTRY_DSN: https://0d5d26943b524e2fb6a9ed3473ec6f56@o131170.ingest.sentry.io/5255579