apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dreamflow-cms-ingress
  namespace: dreamflow
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "dreamflow-cms-letsencrypt-prod"
spec:
  tls:
  - hosts:
    - dreamflow-cms.kreativekws.com
    secretName: dreamflow-cms-tls
  rules:
  - host: dreamflow-cms.kreativekws.com
    http:
      paths:
      - backend:
          serviceName: dreamflow-cms-lb
          servicePort: 80