apiVersion: v1
kind: Service
metadata:
  name: dreamflow-cms
spec:
  selector:
    name: dreamflow-cms
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dreamflow-cms
spec:
  replicas: 3
  selector:
    matchLabels:
      name: dreamflow-cms
  template:
    metadata:
      labels:
        name: dreamflow-cms
    spec:
      containers:
      - name: application
        image: kaynet/dreamflow-cms
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: myregistrysecret