
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dreamflow-cms
  namespace: dreamflow
spec:
  replicas: 2
  selector:
    matchLabels:
      name: dreamflow-cms
  template:
    metadata:
      labels:
        name: dreamflow-cms
    spec:
      containers:
      - name: dreamflow-cms-app
        image: kaynet/dreamflow-cms
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: dreamflow-cms-configmap
        ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: myregsecret
