apiVersion: v1
kind: Service
metadata:
  name: dreamflow-cms-lb
  namespace: dreamflow
spec:
  selector:
    name: dreamflow-cms
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer