# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI-CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_source:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Test on Node.js version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  docker_build_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set enviroment variables
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: kaynet/dreamflow-cms
        tags: ${{ steps.vars.outputs.sha_short }}
  kubernetes_deploy:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set enviroment variables
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Install Doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save kaynet-cluster-1

    - name: Set image to Latest
      run: kubectl set image deployments/dreamflow-cms dreamflow-cms-app=kaynet/dreamflow-cms:${{ steps.vars.outputs.sha_short }}