# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI-CD

on:
  push:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Test on Node.js version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  docker_build_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: kaynet/dreamflow-cms
        tags: latest
  kubernetes_deploy:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save kaynet-cluster-1

    - name: Remove Existing Secret
      run: kubectl delete secret/myregsecret
      continue-on-error: true

    - name: Create Secret for Docker Hub
      run: kubectl create secret docker-registry myregsecret --docker-server=hub.docker.com --docker-username=${{ secrets.DOCKER_USERNAME}} --docker-password=${{ secrets.DOCKER_PASSWORD }} --docker-email=${{ secrets.DOCKER_EMAIL }}

    - name: Deploy to Managed Kubernetes
      run: kubectl apply -f kube/deployment.yml